// <auto-generated />
namespace SibersTestProject.Data.DAL.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCommentary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCommentary));
        
        string IMigrationMetadata.Id
        {
            get { return "201709040928475_AddCommentary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
